### ISSUE TITLE
xssbys3c'

### ISSUE THREAD

**Issue by rohit0x5** [s3c-krd/s3cXSSer#22]
File
~\Downloads\s3cXSSer-main
Error
Manifest file is missing or unreadable
Could not load manifest.

**Comment by s3c-krd** [comment]
Something that commonly happens is that the manifest file isn't named properly. Double check the name (and extension) and be sure that it doesn't end with .txt (for example).

In order to determine this, make sure you aren't hiding file extensions:

Open Windows Explorer
Go to Folder and Search Options > View tab
Uncheck Hide extensions for known file types
Also, note that the naming of the manifest file is, in fact, case sensitive, i.e. manifest.json != MANIFEST.JSON.

OR watch

https://www.youtube.com/watch?v=OQDioEKgSHY

**Comment by rohit0x5** [comment]
xssbys3c\

**Comment by rohit0x5** [comment]
xssbys3c"

**Comment by rohit0x5** [comment]
xssbys3c</>

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
xss

**Comment by rohit0x5** [comment]
brother this thread creted by your tool

**Comment by rohit0x5** [comment]
please add something to on off button idont dont comment you tool this add stared your repo i use this in testphpvulnweb is work on that amzing creation thank you

**Comment by s3c-krd** [comment]
I mentioned in the readme.md how turn it off
